version: "3"

# services define types of containers
# docker-compose automatically networks defined containers
services:
  redis-server:
    image: redis
    ports:
      - "6379:6379"
  node-app:
    restart: always
    build: ./
    ports:
      - "3000:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
